# The name of your plugin as displayed in the Plugins Catalog web UI.
displayName: Decompress Request

# For now, `middleware` is the only type available.
type: middleware

# The import path of your plugin.
import: github.com/Sensedia/traefik-plugin-decompress

# A brief description of what your plugin is doing.
summary: Plugin to decompress compressed requests in gzip

# Configuration data for your plugin.
# This is mandatory,
# and Plugins Catalog will try to execute the plugin with the data you provide as part of its startup validity tests.
testData:
  responseHeader: 200